blank_issues_enabled: false
contact_links:
  - name: Report an issue
    url: https://github.com/better-futures-studio/filament-local-logins/issues
    about: Report issues to the community
  - name: Report a security issue
    url: https://github.com/better-futures-studio/filament-local-logins/security/policy
    about: Learn how to notify us for sensitive bugs
